apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: carizon-device-plugin
spec:
  selector:
    matchLabels:
      name: carizon-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: carizon-device-plugin
    spec:
      hostNetwork: true
      priorityClassName: "system-node-critical"
      containers:
      - image: hub.hobot.cc/dlp/carizon-device-plugin:0.0.1
        name: carizon-device-plugin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
      nodeSelector:
        hobot.cc/bind-horizon-devices: "true"

